---
name: Notification - Load Test
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: The environment to run against
        type: string
        required: true
      type:
        description: The type of load test to run
        type: string
        required: true
      dynamic:
        description: Indicates whether the load test should generate dynamic transactions
        type: boolean
        required: true
      vus:
        description: The number of Virtual Users
        type: string
        required: true
      txs_per_user:
        description: The number of transactions per Virtual User
        type: string
        required: true
      txpool_timeout:
        description: The timeout for waiting for the transaction pool to empty
        type: string
        required: true
      wait_txpool:
        description: Waits for transaction pool to empty before collecting results
        type: boolean
        required: true
      receipts_timeout:
        description: The timeout for waiting for transaction receipts
        type: string
        required: true
      batch_size:
        description: Batch size
        type: string
        required: true
      total_time:
        description: Total Time
        type: string
        required: true
      total_txs:
        description: Total Transactions
        type: string
        required: true
      total_blocks:
        description: Total Blocks
        type: string
        required: true
      avg_txs_per_second:
        description: Average Transactions Per Second
        type: string
        required: true
      max_txs_per_second:
        description: Maximum Transactions Per Second
        type: string
        required: true
      total_gas_used:
        description: Total Gas Used
        type: string
        required: true
      avg_gas_per_tx:
        description: Average Gas Used Per Transaction
        type: string
        required: true
      avg_gas_utilization:
        description: Average Gas Utilization
        type: string
        required: true
      max_gas_utilization:
        description: Maximum Gas Utilization
        type: string
        required: true
      txpool_pending:
        description: Pending Transactions Count
        type: string
        required: true
      txpool_queued:
        description: Queued Transactions Count
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Short SHA
        id: short_sha
        run: echo "value=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          succeed_bnt: 'primary'
          failed_bnt: 'danger'
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Load Test: ${{ inputs.type }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Workflow Run"
                      },
                      "style": "${{ inputs.txpool_pending == '0' && inputs.txpool_queued == '0' && env.succeed_bnt || env.failed_bnt }}",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Commit: *<https://github.com/${{ github.repository }}/tree/${{ github.sha }}|${{ steps.short_sha.outputs.value }}>*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Environment: *${{ inputs.environment }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Instance Type: *${{ vars.AWS_INSTANCE_TYPE }}*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Dynamic Fee TXs: *${{ inputs.dynamic }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "VUs: *${{ inputs.vus }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "TXs/VU: *${{ inputs.txs_per_user }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "TX Pool Timeout: *${{ inputs.txpool_timeout }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Batch Size: *${{ inputs.batch_size }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Receipts Timeout: *${{ inputs.receipts_timeout }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Wait TX Pool To Empty: *${{ inputs.wait_txpool }}*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Pending TXs: *${{ inputs.txpool_pending }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Queued TXs: *${{ inputs.txpool_queued }}*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Total Transactions*\n${{ inputs.total_txs }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Total Blocks*\n${{ inputs.total_blocks }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Average TPS*\n${{ inputs.avg_txs_per_second }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Max TPS*\n${{ inputs.max_txs_per_second }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Average GPT*\n${{ inputs.avg_gas_per_tx }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Total Gas Used*\n${{ inputs.total_gas_used }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Average Gas Utilization*\n${{ inputs.avg_gas_utilization }}%"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Maximum Gas Utilization*\n${{ inputs.max_gas_utilization }}%"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Total Time*\n${{ inputs.total_time }}s"
                    }
                  ]
                }
              ]
            }
